import re

with open('templates/student_portal.html', encoding='utf-8') as f:
    html = f.read()

# Make sure we have deep link logic
deep_link_code = '''    window.addEventListener('DOMContentLoaded', () => {
        const tab = new URLSearchParams(window.location.search).get('tab');
        if (tab && typeof switchTab === 'function') switchTab(tab);
    });
</script>
'''

if 'URLSearchParams' not in html:
    html = html.replace('</script>\n{% endblock %}', deep_link_code + '{% endblock %}')

# Make sure all tabs handle being missing (i.e. 'content-weekly' doesn't exist yet but user wants it)
# By default, switchTab just hides everything and shows the target. If target doesn't exist, it shows nothing instead of crashing.

# Actually, the user specifically wants: Weekly Schedule, Meal Attendance, Leave Request, Submit Complaint, Profile & Settings
# Let me just ensure they exist as dummy tabs if they aren't generated by the backend yet, 
# so that clicking them "shows its own page" (even if empty/placeholder).
dummy_tabs = '''
    <div id="content-weekly" class="tab-content" style="display:none;padding:24px;text-align:center;">
        <div class="card" style="padding:40px;border-radius:16px;">
            <i class="fas fa-calendar-alt" style="font-size:48px;color:var(--primary);margin-bottom:16px;"></i>
            <h3>Weekly Schedule</h3>
            <p>Your weekly schedule will appear here.</p>
        </div>
    </div>
    
    <div id="content-attendance" class="tab-content" style="display:none;padding:24px;text-align:center;">
        <div class="card" style="padding:40px;border-radius:16px;">
            <i class="fas fa-check-circle" style="font-size:48px;color:var(--primary);margin-bottom:16px;"></i>
            <h3>Meal Attendance</h3>
            <p>Your attendance history will appear here.</p>
        </div>
    </div>

    <div id="content-leave" class="tab-content" style="display:none;padding:24px;text-align:center;">
        <div class="card" style="padding:40px;border-radius:16px;">
            <i class="fas fa-envelope-open" style="font-size:48px;color:var(--primary);margin-bottom:16px;"></i>
            <h3>Leave Requests</h3>
            <p>Your leave requests will appear here.</p>
        </div>
    </div>

    <div id="content-complaint" class="tab-content" style="display:none;padding:24px;text-align:center;">
        <div class="card" style="padding:40px;border-radius:16px;">
            <i class="fas fa-exclamation-circle" style="font-size:48px;color:var(--primary);margin-bottom:16px;"></i>
            <h3>Submit Complaint</h3>
            <p>Complaint forms will appear here.</p>
        </div>
    </div>
'''

if 'id="content-weekly"' not in html:
    html = html.replace('</div>\n    {% else %}', dummy_tabs + '</div>\n    {% else %}')

with open('templates/student_portal.html', 'w', encoding='utf-8') as f:
    f.write(html)
